# Generated by Django 5.1.4 on 2025-02-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, default='Cyprus Bank', max_length=200, null=True),
        ),
    ]
