# Generated by Django 5.1.4 on 2025-02-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_apply_for_cards',
            field=models.BooleanField(default=True),
        ),
    ]
