# Generated by Django 5.1.4 on 2025-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_account_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'CHECKING'), ('SAVINGS', 'SAVINGS'), ('MONEY MARKET', 'MONEY MARKET'), ('PLATINUM', 'PLATINUM'), ('CURRENT', 'CURRENT')], max_length=40),
        ),
    ]
