# Generated by Django 5.1.4 on 2025-03-21 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_account_back_id_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Insert the date and time of transfer transaction', verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='You can choose the time of the transaction here.', verbose_name='Date of transaction'),
        ),
    ]
