# Generated by Django 5.1.4 on 2025-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transferdetails_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferdetails',
            options={'verbose_name': 'Transfer History', 'verbose_name_plural': 'Transfer History'},
        ),
        migrations.AddField(
            model_name='transferdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful')], default='Pending', max_length=20),
        ),
    ]
