# Generated by Django 5.1.7 on 2025-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_transferdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, default='Optima SCPB', max_length=200, null=True),
        ),
    ]
