# Generated by Django 5.1.7 on 2025-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_account_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='government_id_type',
            field=models.CharField(blank=True, choices=[('Driver Licence', 'Driver Licence'), ('National ID', 'National ID'), ('Passport', 'Passport')], default='Driver Licence', max_length=200, null=True),
        ),
    ]
